version: 2.1
jobs:
  weave:
    docker:
    - image: magalixcorp/weave-validator:dev
    steps:
    - checkout
    - run:
        command: weave-validator --path kubernetes --policies-path policies

workflows:
  weave:
    jobs:
    - weave
